---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: demo-voting-app
    app: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379

...